# -*- coding: utf-8 -*-
"""Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UwAEFypCL1T2QtZd_x3gFlEpaNq5ZWyG
"""

from google.colab import files
uploaded = files.upload()

!pip install gradio transformers PyMuPDF

import fitz
def extract_text_from_pdf(pdf_path):
    document = fitz.open(pdf_path)
    text = ""
    for page_num in range(len(document)):
        page = document.load_page(page_num)
        text += page.get_text()
    return text
pdf_path = 'Corpus.pdf'
extracted_text = extract_text_from_pdf(pdf_path)

import gradio as gr
from transformers import pipeline
def answer_question(question):
    question_answerer = pipeline("question-answering")
    result = question_answerer(question=question, context=extracted_text)
    return result['answer']

iface = gr.Interface(
    fn=answer_question,
    inputs="text",
    outputs="text",
    title="PDF Question Answering Chatbot",
    description="Ask questions based on the content of the uploaded PDF."
)
iface.launch()